// <auto-generated />
using EaglesAirlines.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EaglesAirlines.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EaglesAirlines.Models.Passageiros", b =>
                {
                    b.Property<string>("CPF")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("email")
                        .HasColumnType("longtext");

                    b.Property<string>("nome_passageiro")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("passaporte")
                        .HasColumnType("longtext");

                    b.Property<string>("telefone")
                        .HasColumnType("longtext");

                    b.HasKey("CPF");

                    b.ToTable("Passageiros");
                });
#pragma warning restore 612, 618
        }
    }
}
